const FAQS = [
  {
    q: "What does this tool actually do?",
    a: "It analyses any digital image and tells you whether it was created by a human or generated by an AI. You upload an image, pick a detection model, and get a verdict with a probability score and supporting visualisations."
  },
  {
    q: "What kinds of images can I upload?",
    a: "Any digital image — photographs, screenshots, scans, digital illustrations, social media exports, or AI art. The models were trained on a wide mix of real and AI-generated content, not just photography."
  },
  {
    q: "Which model should I use?",
    a: "If you are not sure, use Hybrid. It combines spatial and frequency analysis and has the highest overall accuracy. CNN is a reliable alternative if you want faster results with similar precision. Use STM if you need a fully explainable result without GPU hardware. Only use FFT on its own if you are specifically testing frequency-domain detection."
  },
  {
    q: "How accurate are the models?",
    a: "Tested on 2,325 held-out images at Stage 3: Hybrid reached 93.9% AUC and 85.8% F1, CNN reached 93.8% AUC and 85.5% F1, STM reached 83.6% AUC and 75.7% F1, and FFT reached 67.1% AUC and 69.4% F1. Results drop on images from generators not seen during training."
  },
  {
    q: "What is the P(AI) score?",
    a: "It is the raw probability the model assigns to the image being AI-generated. Zero means the model is confident it is authentic. One means it is confident it is AI. The verdict flips at 0.5. Confidence is the probability of whichever side won, so it runs from 50% at that boundary up to 100% at either extreme."
  },
  {
    q: "Why does the STM model take longer?",
    a: "STM runs entirely on CPU and manually extracts 1,822 features per image (edge gradients, micro-textures, frequency coefficients, colour statistics, and noise patterns) before passing them to LightGBM. This feature extraction step takes longer than a single GPU forward pass used by the other three models."
  },
  {
    q: "What do the visualisations show?",
    a: "CNN and Hybrid show a Grad-CAM heatmap highlighting which regions most influenced the verdict. FFT and Hybrid show a frequency spectrogram where unusual energy concentrations can indicate AI generation. STM shows a feature importance chart breaking down which of the five feature groups contributed most to the decision."
  },
  {
    q: "Are my images saved or stored?",
    a: "No. Images are processed in memory and discarded after inference. Only metadata is saved: filename, model used, verdict, confidence score, and timestamp. This is used for the session history log only."
  },
]

const MODELS = [
  {
    name: 'CNN',
    full: 'Spatial CNN',
    speed: 'Fast',
    auc: '93.8%',
    desc: 'ResNet-50 backbone trained to detect spatial artifacts — upsampling patterns, texture irregularities, and GAN-specific structural traces in the pixel domain.',
  },
  {
    name: 'FFT',
    full: 'Frequency FFT',
    speed: 'Fast',
    auc: '67.1%',
    desc: 'Analyses four learned radial frequency bands in the Fourier spectrum. Effective for detecting diffusion model signatures but limited on mixed GAN and diffusion datasets.',
  },
  {
    name: 'Hybrid',
    full: 'Hybrid Fusion',
    speed: 'Slower',
    auc: '93.9%',
    desc: 'Combines 2048-dim CNN spatial features and 256-dim FFT spectral features through a learned fusion network. Highest overall accuracy across all test conditions.',
  },
  {
    name: 'STM',
    full: 'Handcrafted STM',
    speed: 'Slowest',
    auc: '83.6%',
    desc: '1,822 handcrafted features (HOG, LBP, DCT, colour stats, noise residual) classified by LightGBM. No neural network. Fully explainable and runs without a GPU.',
  },
]

function FaqItem({ q, a }) {
  return (
    <div className="py-3 border-b border-cappuccino/30 last:border-0">
      <p className="text-sm font-bold text-espresso mb-1">{q}</p>
      <p className="text-xs text-roast leading-relaxed">{a}</p>
    </div>
  )
}

function Section({ title, children }) {
  return (
    <div className="card p-6">
      <p className="text-lg font-black text-espresso mb-4">{title}</p>
      {children}
    </div>
  )
}

export default function FaqPage() {
  return (
    <div className="max-w-5xl mx-auto">
      <h1 className="page-title">Help and Reference</h1>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">

        <div>
          <Section title="Frequently Asked Questions">
            <div className="space-y-0">
              {FAQS.map((item, i) => (
                <FaqItem key={i} q={item.q} a={item.a} />
              ))}
            </div>
          </Section>
        </div>

        <div className="space-y-4">
          <Section title="Model Reference">
            <p className="text-xs text-roast leading-relaxed mb-4">
              All four models were trained on 15,500 images across six generator families and evaluated on a held-out test set of 2,325 images. AUC scores are from Stage 3 testing.
            </p>
            <div className="space-y-0">
              {MODELS.map((m) => (
                <div key={m.name} className="py-3 border-b border-cappuccino/30 last:border-0">
                  <div className="flex items-center justify-between mb-1">
                    <p className="text-sm font-black text-espresso">
                      {m.name}
                      <span className="text-xs font-normal text-roast ml-2">{m.full}</span>
                    </p>
                    <div className="flex items-center gap-2">
                      <span className="text-xs font-semibold text-roast">AUC {m.auc}</span>
                      <span className="text-xs font-semibold text-roast bg-cream border border-cappuccino/60 rounded-md px-2 py-0.5">{m.speed}</span>
                    </div>
                  </div>
                  <p className="text-xs text-roast leading-relaxed">{m.desc}</p>
                </div>
              ))}
            </div>
          </Section>

          <Section title="Understanding Metrics">
            <div className="space-y-0">
              {[
                { name: 'P(AI)', desc: 'Raw probability the image is AI-generated. Below 0.5 = authentic verdict. Above 0.5 = AI verdict.' },
                { name: 'Confidence', desc: 'The probability of whichever side won, so it runs from 50% at the 0.5 boundary up to 100% at either extreme. 95% means the model is strongly committed to its verdict.' },
                { name: 'AUC-ROC', desc: 'Threshold-independent quality measure across all operating points. 1.0 is perfect, 0.5 is random chance.' },
                { name: 'Contrast', desc: 'Pixel brightness variation scaled 0-100. Natural images typically score 30-70. AI smoothing can push this lower.' },
                { name: 'Sensor Noise', desc: 'High-frequency residual after subtracting a blurred version. Real sensors leave physical noise patterns that AI images tend to lack.' },
              ].map((m) => (
                <div key={m.name} className="py-2.5 border-b border-cappuccino/30 last:border-0">
                  <p className="text-sm font-bold text-espresso">{m.name}</p>
                  <p className="text-xs text-roast mt-0.5 leading-relaxed">{m.desc}</p>
                </div>
              ))}
            </div>
          </Section>
        </div>

      </div>
    </div>
  )
}